// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CJ.Plug.Models.Migrations.MainDb
{
    [DbContext(typeof(MainDbContext))]
    partial class MainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("ActionData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionIdentityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionPlugRootDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionPlugType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputAndOutput")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArray")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsBrowsable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInitVariable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInput")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOutput")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsValueFromOtherVariable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlugDataZoneId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlugDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SN")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceValuePlugDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceValueVariableId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceValueVariableName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageDriver")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageDriverTypeName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("UIHint")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlugDataZoneId");

                    b.ToTable("ActionDatas", (string)null);
                });

            modelBuilder.Entity("ActionVariableData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionIdentityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionRootDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputAndOutput")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArray")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsBrowsable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInitVariable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInput")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOutput")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsValueFromOtherVariable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlugDataZoneId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlugDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SN")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceValuePlugDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceValueVariableId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceValueVariableName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageDriver")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageDriverTypeName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("UIHint")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlugDataZoneId");

                    b.ToTable("ActionVariableDatas", (string)null);
                });

            modelBuilder.Entity("CJ.Plug.Models.Job.BaseJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EngineInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IncidentCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobCategory")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("JobCorrelationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobDataFolderPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobSubStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentJobCorrelationId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentJobId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Jobs", (string)null);

                    b.HasDiscriminator<string>("JobCategory").HasValue("BaseJob");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CJ.Plug.Models.MCPTools.MCPTool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePlugId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolSettingsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MCPTools", (string)null);
                });

            modelBuilder.Entity("CJ.Plug.Models.Plug.Plug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivityJsonData")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityMetaData")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityNodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreateType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Creater")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT");

                    b.Property<string>("GuiJsonData")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsContainerPlug")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRootPlug")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<bool>("OnlyExecuteAction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentPlugDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlugSettingsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlugTypeKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RealValuePath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowInPlugLibrary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolCommandLineShema")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ToolId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToolName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolVersionPath")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ToolVersions")
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerPlugDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerPlugId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkPath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Plugs", (string)null);

                    b.HasDiscriminator().HasValue("Plug");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CJ.Plug.Models.Plug.PlugVariable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputAndOutput")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArray")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsBrowsable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInitVariable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInput")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOutput")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsValueFromOtherVariable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlugId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceValuePlugDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceValueVariableId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceValueVariableName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageDriver")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageDriverTypeName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("UIHint")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlugId");

                    b.ToTable("PlugVariables", (string)null);
                });

            modelBuilder.Entity("CJ.Plug.Models.Relation.CommonRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelationCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationSetting")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationType")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoleAId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleAName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoleBId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleBName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Relations", (string)null);
                });

            modelBuilder.Entity("CJ.Plug.Models.Relation.PlugToPlugAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlugActionDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlugActionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlugDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlugId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlugToolVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationshipType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PlugToPlugActions", (string)null);
                });

            modelBuilder.Entity("CJ.Plug.Models.Shared.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manager")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("CJ.Plug.Models.Shared.FileInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileExtension")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileSize")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileType")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileUploadDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileUploadPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileUploadTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileUploadType")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileUploader")
                        .HasColumnType("TEXT");

                    b.Property<string>("MinioPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("SandBoxPath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FileInformations", (string)null);
                });

            modelBuilder.Entity("CJ.Plug.Models.Shared.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CJ.Plug.Models.Shared.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("CJ.Plug.Models.Station.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStarted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StationBasePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("StationCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("StationIp")
                        .HasColumnType("TEXT");

                    b.Property<string>("StationName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StationStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stations", (string)null);
                });

            modelBuilder.Entity("CJ.Plug.Models.Station.StationConfigTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("StationIp")
                        .HasColumnType("TEXT");

                    b.Property<string>("StationStatus")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StationConfigTables", (string)null);
                });

            modelBuilder.Entity("CJ.Plug.Models.Station.Tool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommandParameter")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsBrowsable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsSystemInitTool")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToolCompany")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolLocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolVersion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tools", (string)null);
                });

            modelBuilder.Entity("CJ.Plug.Models.Station.ToolConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommandParameter")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsDisabled")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StationConfigTableId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ToolId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToolName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolVersion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StationConfigTableId");

                    b.ToTable("ToolConfig");
                });

            modelBuilder.Entity("DataFlowData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputAndOutput")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArray")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsBrowsable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInitVariable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInput")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOutput")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsValueFromOtherVariable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlugDataZoneId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PortLinkData")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePlugDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceValuePlugDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceValueVariableId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceValueVariableName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceVariableId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceVariableName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageDriver")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageDriverTypeName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetPlugDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TargetVariableId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetVariableName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("UIHint")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlugDataZoneId");

                    b.ToTable("DataFlowDatas", (string)null);
                });

            modelBuilder.Entity("FlowchartData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputAndOutput")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArray")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsBrowsable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInitVariable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInput")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOutput")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsValueFromOtherVariable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlugDataZoneId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlugDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceValuePlugDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceValueVariableId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceValueVariableName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageDriver")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageDriverTypeName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("UIHint")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlugDataZoneId");

                    b.ToTable("FlowchartDatas", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PDZVariable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionIdentityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputAndOutput")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArray")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsBrowsable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInitVariable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInput")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOutput")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsValueFromOtherVariable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlugActionDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlugActionType")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlugDataZoneId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlugDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SN")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("SaveToPlug")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceValuePlugDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceValueVariableId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceValueVariableName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageDriver")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageDriverTypeName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("UIHint")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlugDataZoneId");

                    b.ToTable("PDZVariable");
                });

            modelBuilder.Entity("PlugData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Creater")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputAndOutput")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArray")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsBrowsable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInitVariable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInput")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOutput")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsValueFromOtherVariable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<bool>("OnlyExecuteAction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentPlugDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlugDataZoneId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlugDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlugPosition")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlugType")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlugTypeKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceValuePlugDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceValueVariableId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceValueVariableName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageDriver")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageDriverTypeName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("UIHint")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkPath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlugDataZoneId");

                    b.ToTable("PlugDatas", (string)null);
                });

            modelBuilder.Entity("PlugDataZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PDZId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PDZWorkPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlugDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerPlugDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PlugDataZones", (string)null);
                });

            modelBuilder.Entity("PlugStatusData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputAndOutput")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArray")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsBrowsable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInitVariable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInput")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOutput")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsValueFromOtherVariable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlugDataZoneId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlugDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceValuePlugDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceValueVariableId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceValueVariableName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageDriver")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageDriverTypeName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("UIHint")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlugDataZoneId");

                    b.ToTable("PlugStatusDatas", (string)null);
                });

            modelBuilder.Entity("PlugVariableData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputAndOutput")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArray")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsBrowsable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInitVariable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInput")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOutput")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsValueFromOtherVariable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlugDataZoneId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlugDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceValuePlugDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceValueVariableId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceValueVariableName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageDriver")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageDriverTypeName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("UIHint")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlugDataZoneId");

                    b.ToTable("PlugVariableDatas", (string)null);
                });

            modelBuilder.Entity("CJ.Plug.Models.Job.PlugJob", b =>
                {
                    b.HasBaseType("CJ.Plug.Models.Job.BaseJob");

                    b.Property<string>("PlugDefinitionId")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("PlugJob");
                });

            modelBuilder.Entity("CJ.Plug.Models.Job.ProcessJob", b =>
                {
                    b.HasBaseType("CJ.Plug.Models.Job.BaseJob");

                    b.Property<string>("JournalData")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessDefinitionId")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("ProcessJob");
                });

            modelBuilder.Entity("CJ.Plug.Models.Job.ToolJob", b =>
                {
                    b.HasBaseType("CJ.Plug.Models.Job.BaseJob");

                    b.Property<string>("ExecuteResultData")
                        .HasColumnType("TEXT");

                    b.Property<string>("StationIp")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolVersion")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("ToolJob");
                });

            modelBuilder.Entity("CJ.Plug.Models.PlugProcess.Process", b =>
                {
                    b.HasBaseType("CJ.Plug.Models.Plug.Plug");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Version")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Process");
                });

            modelBuilder.Entity("MarketPlug", b =>
                {
                    b.HasBaseType("CJ.Plug.Models.Plug.Plug");

                    b.Property<string>("Base64ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("MarketImageBytes")
                        .HasColumnType("BLOB");

                    b.Property<string>("MarketName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RootPlugID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsersCount")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("MarketPlug");
                });

            modelBuilder.Entity("ActionData", b =>
                {
                    b.HasOne("PlugDataZone", "PlugDataZone")
                        .WithMany("ActionDatas")
                        .HasForeignKey("PlugDataZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlugDataZone");
                });

            modelBuilder.Entity("ActionVariableData", b =>
                {
                    b.HasOne("PlugDataZone", "PlugDataZone")
                        .WithMany("ActionVariableDatas")
                        .HasForeignKey("PlugDataZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlugDataZone");
                });

            modelBuilder.Entity("CJ.Plug.Models.Plug.PlugVariable", b =>
                {
                    b.HasOne("CJ.Plug.Models.Plug.Plug", "Plug")
                        .WithMany("PlugVariables")
                        .HasForeignKey("PlugId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Plug");
                });

            modelBuilder.Entity("CJ.Plug.Models.Station.ToolConfig", b =>
                {
                    b.HasOne("CJ.Plug.Models.Station.StationConfigTable", "StationConfigTable")
                        .WithMany("ToolConfigs")
                        .HasForeignKey("StationConfigTableId");

                    b.Navigation("StationConfigTable");
                });

            modelBuilder.Entity("DataFlowData", b =>
                {
                    b.HasOne("PlugDataZone", "PlugDataZone")
                        .WithMany("DataFlowDatas")
                        .HasForeignKey("PlugDataZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlugDataZone");
                });

            modelBuilder.Entity("FlowchartData", b =>
                {
                    b.HasOne("PlugDataZone", "PlugDataZone")
                        .WithMany("FlowchartDatas")
                        .HasForeignKey("PlugDataZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlugDataZone");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("CJ.Plug.Models.Shared.UserRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("CJ.Plug.Models.Shared.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("CJ.Plug.Models.Shared.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("CJ.Plug.Models.Shared.UserRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CJ.Plug.Models.Shared.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("CJ.Plug.Models.Shared.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PDZVariable", b =>
                {
                    b.HasOne("PlugDataZone", "PlugDataZone")
                        .WithMany("PDZVariables")
                        .HasForeignKey("PlugDataZoneId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("PlugDataZone");
                });

            modelBuilder.Entity("PlugData", b =>
                {
                    b.HasOne("PlugDataZone", "PlugDataZone")
                        .WithMany("PlugDatas")
                        .HasForeignKey("PlugDataZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlugDataZone");
                });

            modelBuilder.Entity("PlugStatusData", b =>
                {
                    b.HasOne("PlugDataZone", "PlugDataZone")
                        .WithMany("PlugStatusDatas")
                        .HasForeignKey("PlugDataZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlugDataZone");
                });

            modelBuilder.Entity("PlugVariableData", b =>
                {
                    b.HasOne("PlugDataZone", "PlugDataZone")
                        .WithMany("PlugVariableDatas")
                        .HasForeignKey("PlugDataZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlugDataZone");
                });

            modelBuilder.Entity("CJ.Plug.Models.Plug.Plug", b =>
                {
                    b.Navigation("PlugVariables");
                });

            modelBuilder.Entity("CJ.Plug.Models.Station.StationConfigTable", b =>
                {
                    b.Navigation("ToolConfigs");
                });

            modelBuilder.Entity("PlugDataZone", b =>
                {
                    b.Navigation("ActionDatas");

                    b.Navigation("ActionVariableDatas");

                    b.Navigation("DataFlowDatas");

                    b.Navigation("FlowchartDatas");

                    b.Navigation("PDZVariables");

                    b.Navigation("PlugDatas");

                    b.Navigation("PlugStatusDatas");

                    b.Navigation("PlugVariableDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
